---
abstract: 'very basic, commonly used Math funcs'
author:
  - 'Linda Walsh (LAWALSH@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: 6.82
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.88, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Simple
no_index:
  directory:
    - t
    - inc
requires:
  Xporter: v0.0.11
version: v2.1.2
